# Generated by Django 2.2.4 on 2019-08-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('channel_id', models.TextField()),
                ('create_at', models.TextField()),
            ],
            options={
                'db_table': 'received',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('valid', models.IntegerField(blank=True, null=True)),
                ('channel_id', models.TextField()),
                ('create_at', models.TextField()),
            ],
            options={
                'db_table': 'reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('response', models.TextField()),
                ('create_at', models.TextField()),
                ('channel_id', models.TextField()),
                ('channel_type', models.TextField()),
                ('priority', models.IntegerField()),
            ],
            options={
                'db_table': 'statements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField()),
                ('globaltalk', models.IntegerField()),
                ('mute', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
